name: Multi-OS System Check

on:
  push:
  workflow_dispatch:

jobs:
  system-info:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: System info (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          echo "=== sistema operativo ===" > system-info.txt
          uname -a >> system-info.txt
          
          echo "=== arquitectura ===" >> system-info.txt
          uname -m >> system-info.txt

          echo "=== variables de entorno ===" >> system-info.txt
          env >> system-info.txt

      - name: System info (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          "=== sistema operativo ===" | Out-File system-info.txt
          systeminfo | Out-File -Append system-info.txt

          "=== arquitectura ===" | Out-File -Append system-info.txt
          Get-CimInstance Win32_OperatingSystem | Select-Object OSArchitecture | Out-File -Append system-info.txt

          "=== variables de entorno ===" | Out-File -Append system-info.txt
          Get-ChildItem Env: | Out-File -Append system-info.txt

      - name: Upload System Info
        uses: actions/upload-artifact@v4
        with:
          name: system-info-${{ matrix.os }}
          path: system-info.txt
